# Support Vector Machine in Python

## SVM Diagram
![alt text](SVM.jpg)

In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [10]:
# Read and display data
iris = pd.read_csv('Iris_Flower.csv')
iris.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [11]:
# train test split
from sklearn.model_selection import train_test_split


# Separate the independent variables from the dependent variables
x = iris.iloc[:,:-1]
y = iris.iloc[:,4]


# Train and fit the model
x_train,x_test, y_train, y_test=train_test_split(x,y,test_size=0.30)

from sklearn.svm import SVC
model = SVC()

model.fit(x_train, y_train)

SVC()

In [12]:
# Make predictions from the trained model
prediction = model.predict(x_test)


# Import the classification report and confusion matrix
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test,prediction))

[[13  0  0]
 [ 0 14  0]
 [ 0  1 17]]


In [13]:
print(classification_report(y_test, prediction))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        13
Iris-versicolor       0.93      1.00      0.97        14
 Iris-virginica       1.00      0.94      0.97        18

       accuracy                           0.98        45
      macro avg       0.98      0.98      0.98        45
   weighted avg       0.98      0.98      0.98        45

